substitutions:
  bambuddy_url: !secret bambuddy_url
  bambuddy_api_key: !secret bambuddy_api_key

esphome:
  name: spool-reader
  friendly_name: spool-reader

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

external_components:
  - source:
      type: git
      url: https://github.com/BluetriX/esphome-CST328-Touch
    components: [cst328]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret spool_reader_api_encryption_key

ota:
  - platform: esphome
    password: !secret spool_reader_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Spool-Reader Fallback Hotspot"
    password: !secret spool_reader_ap_password
    
captive_portal:

packages:
  display: !include spool-reader/hw-display.yaml
  fonts: !include spool-reader/ui-fonts.yaml
  nfc: !include spool-reader/hw-nfc.yaml
  bambuddy: !include spool-reader/api-bambuddy.yaml
  styles: !include spool-reader/ui-styles.yaml
  page_idle: !include spool-reader/page-idle.yaml
  page_filament: !include spool-reader/page-filament.yaml
  page_details: !include spool-reader/page-details.yaml
  triggers: !include spool-reader/pages-triggers.yaml